server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 124.222.168.87
    port: 6379
    timeout: 1800000

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 5NMQ-l5wpJmhhj5LBn16iFKgkTD9gRdy4copKpLP
  secretKey: R29qfn8V9KW4sPbSHktmtPjlWTR64niSIa82mdmg
  bucket: qx--blog

tencent:
  cos:
    #腾讯云对象存储参数
    #腾讯云账户secretId，secretKey
    secretId: AKIDzuc6KM8eV5OcniNn1Tl9IG0UnsfBQP7Y
    secretKey: ECziRvhVAdqpY1DD2asuf9PPAftulRsE
    #存储桶名称
    buckerName: quit-blog-1316955252
    #地域
    region: ap-shanghai
    #请求域名（使用对应的存储桶和对应的地域）
    url: https://quit-blog-1316955252.cos.ap-shanghai.myqcloud.com